"""Alembic environment for async migrations."""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import URL, pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

from aevorex.config import settings
from aevorex.db.models import Base

# this is the Alembic Config object, which provides
# the values of the [alembic] section of the .ini file
# in as Python dictionary.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Model's MetaData object for 'autogenerate' support
target_metadata = Base.metadata

# Database objects that exist on purpose but cannot be expressed in the
# SQLAlchemy model metadata. Autogenerate compares the live schema against the
# models, sees these as orphans, and emits a DROP for them.
#
# This is not hypothetical: revision 4839e42f32c8 was autogenerated and
# silently dropped `uq_price_history_event`, removing the database-level
# guarantee against duplicate price events. The Python guard in
# PipelineRunner._upsert_price_history held, so nothing broke visibly — which
# is precisely what makes the failure mode dangerous.
#
# `uq_price_history_event` is an expression index
# (COALESCE(price, -1), COALESCE(source_event_id, '')), needed because
# Postgres treats NULLs as distinct in a unique index and both of those
# columns are legitimately nullable. SQLAlchemy cannot round-trip it, so it
# is created in migrations by hand and shielded here.
AUTOGENERATE_IGNORED_INDEXES = {
    "uq_price_history_event",
}


# Tables that exist on purpose but are not ORM models, so autogenerate sees
# them as orphans and emits a drop_table for each one. `analysis_v1_snapshot`
# is the pre-rebuild copy of the v1 scores, kept for before/after comparison;
# an unreviewed `alembic upgrade` must not be able to delete it.
AUTOGENERATE_IGNORED_TABLES = {
    "analysis_v1_snapshot",
}


def include_object(obj, name, type_, reflected, compare_to):
    """Keep autogenerate from dropping hand-maintained schema objects."""
    if type_ == "index" and name in AUTOGENERATE_IGNORED_INDEXES:
        return False
    if type_ == "table" and name in AUTOGENERATE_IGNORED_TABLES:
        return False
    return True


def get_database_url() -> URL:
    """Get async PostgreSQL URL from settings."""
    return URL.create(
        "postgresql+asyncpg",
        username=settings.db_user,
        password=settings.db_password.get_secret_value(),
        host=settings.db_host,
        port=settings.db_port,
        database=settings.db_name,
    )


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.
    """
    url = get_database_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    """Run migrations on a synchronous connection."""
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.
    """
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = get_database_url().render_as_string(
        hide_password=False
    )

    connectable = create_async_engine(
        get_database_url(),
        poolclass=pool.NullPool,
    )

    # connect(), not begin(): the transaction has to be Alembic's, not ours.
    # A migration that needs to step outside the transaction — CREATE INDEX
    # CONCURRENTLY, which Postgres refuses to run inside one — does it via
    # op.get_context().autocommit_block(), and that asserts Alembic owns the
    # transaction it's being asked to commit. With begin() wrapping the
    # connection here, Alembic's own transaction handle is None and the block
    # fails with a bare AssertionError. do_run_migrations already opens the
    # transaction through context.begin_transaction().
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
        await connection.commit()

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    import asyncio

    asyncio.run(run_migrations_online())
