"""Alembic script template for migrations."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308a36e51aca'
down_revision = '5701119774d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('median_list_price', sa.Integer(), nullable=True),
    sa.Column('median_sale_price', sa.Integer(), nullable=True),
    sa.Column('avg_days_on_market', sa.Float(), nullable=True),
    sa.Column('sale_to_list_pct', sa.Float(), nullable=True),
    sa.Column('yoy_price_change_pct', sa.Float(), nullable=True),
    sa.Column('price_drop_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_snapshots_zip_date', 'market_snapshots', ['zip_code', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_market_snapshots_source'), 'market_snapshots', ['source'], unique=False)
    op.create_index(op.f('ix_market_snapshots_zip_code'), 'market_snapshots', ['zip_code'], unique=False)
    op.create_table('location_scores',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('pedestrian_score', sa.Float(), nullable=True),
    sa.Column('cycling_score', sa.Float(), nullable=True),
    sa.Column('transit_score', sa.Float(), nullable=True),
    sa.Column('car_score', sa.Float(), nullable=True),
    sa.Column('parks_score', sa.Float(), nullable=True),
    sa.Column('groceries_score', sa.Float(), nullable=True),
    sa.Column('shopping_score', sa.Float(), nullable=True),
    sa.Column('nightlife_score', sa.Float(), nullable=True),
    sa.Column('restaurants_score', sa.Float(), nullable=True),
    sa.Column('cafes_score', sa.Float(), nullable=True),
    sa.Column('daycares_score', sa.Float(), nullable=True),
    sa.Column('primary_schools_score', sa.Float(), nullable=True),
    sa.Column('high_schools_score', sa.Float(), nullable=True),
    sa.Column('quiet_score', sa.Float(), nullable=True),
    sa.Column('vibrant_score', sa.Float(), nullable=True),
    sa.Column('wellness_score', sa.Float(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('points_of_interest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pois_property_source', 'points_of_interest', ['property_id', 'source'], unique=False)
    op.create_index(op.f('ix_points_of_interest_property_id'), 'points_of_interest', ['property_id'], unique=False)
    op.create_index(op.f('ix_points_of_interest_source'), 'points_of_interest', ['source'], unique=False)
    op.create_table('property_comps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('comp_address', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('sold_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_property_comps_property_source', 'property_comps', ['property_id', 'source'], unique=False)
    op.create_index(op.f('ix_property_comps_property_id'), 'property_comps', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_comps_source'), 'property_comps', ['source'], unique=False)
    op.create_table('property_features',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('heating', sa.String(length=100), nullable=True),
    sa.Column('cooling', sa.String(length=100), nullable=True),
    sa.Column('flooring', sa.String(length=150), nullable=True),
    sa.Column('construction_material', sa.String(length=100), nullable=True),
    sa.Column('roof', sa.String(length=100), nullable=True),
    sa.Column('foundation', sa.String(length=100), nullable=True),
    sa.Column('interior_features', sa.Text(), nullable=True),
    sa.Column('appliances', sa.Text(), nullable=True),
    sa.Column('laundry_features', sa.String(length=150), nullable=True),
    sa.Column('water_source', sa.String(length=50), nullable=True),
    sa.Column('sewer', sa.String(length=50), nullable=True),
    sa.Column('utilities', sa.Text(), nullable=True),
    sa.Column('furnished', sa.String(length=30), nullable=True),
    sa.Column('direction_faces', sa.String(length=20), nullable=True),
    sa.Column('raw_amenities', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('school_type', sa.String(length=20), nullable=True),
    sa.Column('grades', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schools_property_source', 'schools', ['property_id', 'source'], unique=False)
    op.create_index(op.f('ix_schools_property_id'), 'schools', ['property_id'], unique=False)
    op.create_index(op.f('ix_schools_source'), 'schools', ['source'], unique=False)
    op.create_table('transport_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('stop_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transport_stops_property', 'transport_stops', ['property_id'], unique=False)
    op.create_index(op.f('ix_transport_stops_property_id'), 'transport_stops', ['property_id'], unique=False)
    op.create_index(op.f('ix_transport_stops_source'), 'transport_stops', ['source'], unique=False)
    op.add_column('properties', sa.Column('apn', sa.String(length=64), nullable=True))
    op.add_column('properties', sa.Column('county', sa.String(length=100), nullable=True))
    op.create_index('idx_properties_apn_state', 'properties', ['apn', 'state'], unique=False)
    op.create_index(op.f('ix_properties_apn'), 'properties', ['apn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_apn'), table_name='properties')
    op.drop_index('idx_properties_apn_state', table_name='properties')
    op.drop_column('properties', 'county')
    op.drop_column('properties', 'apn')
    op.drop_index(op.f('ix_transport_stops_source'), table_name='transport_stops')
    op.drop_index(op.f('ix_transport_stops_property_id'), table_name='transport_stops')
    op.drop_index('idx_transport_stops_property', table_name='transport_stops')
    op.drop_table('transport_stops')
    op.drop_index(op.f('ix_schools_source'), table_name='schools')
    op.drop_index(op.f('ix_schools_property_id'), table_name='schools')
    op.drop_index('idx_schools_property_source', table_name='schools')
    op.drop_table('schools')
    op.drop_table('property_features')
    op.drop_index(op.f('ix_property_comps_source'), table_name='property_comps')
    op.drop_index(op.f('ix_property_comps_property_id'), table_name='property_comps')
    op.drop_index('idx_property_comps_property_source', table_name='property_comps')
    op.drop_table('property_comps')
    op.drop_index(op.f('ix_points_of_interest_source'), table_name='points_of_interest')
    op.drop_index(op.f('ix_points_of_interest_property_id'), table_name='points_of_interest')
    op.drop_index('idx_pois_property_source', table_name='points_of_interest')
    op.drop_table('points_of_interest')
    op.drop_table('location_scores')
    op.drop_index(op.f('ix_market_snapshots_zip_code'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_source'), table_name='market_snapshots')
    op.drop_index('idx_market_snapshots_zip_date', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
