"""Alembic script template for migrations."""


# revision identifiers, used by Alembic.
revision = '34c81b9e61c7'
down_revision = 'e5b207c9d418'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
