"""Alembic script template for migrations."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4839e42f32c8'
down_revision = 'b7e2d94c5a11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_property_scores_property_strategy', table_name='property_scores')
    op.drop_index('idx_property_scores_strategy_score', table_name='property_scores')
    op.drop_index('ix_property_scores_property_id', table_name='property_scores')
    op.drop_index('ix_property_scores_strategy', table_name='property_scores')
    op.drop_table('property_scores')
    op.drop_table('property_analysis_pre_backfill')
    op.drop_index('uq_price_history_event', table_name='price_history')
    op.add_column('properties', sa.Column('has_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'has_open')
    op.create_index('uq_price_history_event', 'price_history', ['property_id', 'source', 'event', 'event_date', sa.text("COALESCE(price, '-1'::integer)"), sa.text("COALESCE(source_event_id, ''::character varying)")], unique=True)
    op.create_table('property_analysis_pre_backfill',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('motivated_seller_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('motivated_seller_rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivated_seller_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('motivated_seller_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fix_flip_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fix_flip_rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fix_flip_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fix_flip_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('buy_hold_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('buy_hold_rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('buy_hold_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('buy_hold_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('str_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('str_rationale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('str_factors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('str_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scoring_config_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.create_table('property_scores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('property_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rationale', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='property_scores_property_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='property_scores_pkey')
    )
    op.create_index('ix_property_scores_strategy', 'property_scores', ['strategy'], unique=False)
    op.create_index('ix_property_scores_property_id', 'property_scores', ['property_id'], unique=False)
    op.create_index('idx_property_scores_strategy_score', 'property_scores', ['strategy', 'score'], unique=False)
    op.create_index('idx_property_scores_property_strategy', 'property_scores', ['property_id', 'strategy'], unique=True)
    # ### end Alembic commands ###
