"""Alembic script template for migrations."""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5701119774d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_scrapes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('scrape_status', sa.String(length=50), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_scrapes_source_created', 'raw_scrapes', ['source', 'created_at'], unique=False)
    op.create_index('idx_raw_scrapes_status', 'raw_scrapes', ['scrape_status'], unique=False)
    op.create_index(op.f('ix_raw_scrapes_external_id'), 'raw_scrapes', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_scrapes_source'), 'raw_scrapes', ['source'], unique=False)
    op.create_index(op.f('ix_raw_scrapes_url'), 'raw_scrapes', ['url'], unique=False)
    op.create_table('scrape_errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_errors_error_type', 'scrape_errors', ['error_type'], unique=False)
    op.create_index('idx_scrape_errors_source_created', 'scrape_errors', ['source', 'created_at'], unique=False)
    op.create_index(op.f('ix_scrape_errors_source'), 'scrape_errors', ['source'], unique=False)
    op.create_index(op.f('ix_scrape_errors_url'), 'scrape_errors', ['url'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_scrape_id', sa.UUID(), nullable=True),
    sa.Column('zillow_id', sa.String(length=255), nullable=True),
    sa.Column('redfin_id', sa.String(length=255), nullable=True),
    sa.Column('realtor_id', sa.String(length=255), nullable=True),
    sa.Column('primary_source', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('listing_status', sa.String(length=50), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('price_variance', sa.Float(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('listing_url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_scrape_id'], ['raw_scrapes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_properties_address_zip', 'properties', ['address', 'zip_code'], unique=False)
    op.create_index('idx_properties_created_at', 'properties', ['created_at'], unique=False)
    op.create_index('idx_properties_source_count', 'properties', ['source_count'], unique=False)
    op.create_index('idx_properties_state_city', 'properties', ['state', 'city'], unique=False)
    op.create_index(op.f('ix_properties_address'), 'properties', ['address'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_listing_status'), 'properties', ['listing_status'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_realtor_id'), 'properties', ['realtor_id'], unique=False)
    op.create_index(op.f('ix_properties_redfin_id'), 'properties', ['redfin_id'], unique=False)
    op.create_index(op.f('ix_properties_state'), 'properties', ['state'], unique=False)
    op.create_index(op.f('ix_properties_zillow_id'), 'properties', ['zillow_id'], unique=False)
    op.create_index(op.f('ix_properties_zip_code'), 'properties', ['zip_code'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('lead_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leads_property_type', 'leads', ['property_id', 'lead_type'], unique=False)
    op.create_index('idx_leads_score', 'leads', ['score'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_index(op.f('ix_leads_lead_type'), 'leads', ['lead_type'], unique=False)
    op.create_index(op.f('ix_leads_property_id'), 'leads', ['property_id'], unique=False)
    op.create_table('open_houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_open_houses_property_source', 'open_houses', ['property_id', 'source'], unique=False)
    op.create_index('idx_open_houses_time_range', 'open_houses', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_open_houses_property_id'), 'open_houses', ['property_id'], unique=False)
    op.create_index(op.f('ix_open_houses_source'), 'open_houses', ['source'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_event_date', 'price_history', ['event_date'], unique=False)
    op.create_index('idx_price_history_property_source', 'price_history', ['property_id', 'source'], unique=False)
    op.create_index(op.f('ix_price_history_property_id'), 'price_history', ['property_id'], unique=False)
    op.create_index(op.f('ix_price_history_source'), 'price_history', ['source'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_property_images_property_source', 'property_images', ['property_id', 'source'], unique=False)
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_images_source'), 'property_images', ['source'], unique=False)
    op.create_table('tax_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=True),
    sa.Column('assessed_value', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tax_history_property_year', 'tax_history', ['property_id', 'tax_year'], unique=False)
    op.create_index('idx_tax_history_source', 'tax_history', ['source'], unique=False)
    op.create_index(op.f('ix_tax_history_property_id'), 'tax_history', ['property_id'], unique=False)
    op.create_index(op.f('ix_tax_history_source'), 'tax_history', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_history_source'), table_name='tax_history')
    op.drop_index(op.f('ix_tax_history_property_id'), table_name='tax_history')
    op.drop_index('idx_tax_history_source', table_name='tax_history')
    op.drop_index('idx_tax_history_property_year', table_name='tax_history')
    op.drop_table('tax_history')
    op.drop_index(op.f('ix_property_images_source'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_index('idx_property_images_property_source', table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_price_history_source'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_property_id'), table_name='price_history')
    op.drop_index('idx_price_history_property_source', table_name='price_history')
    op.drop_index('idx_price_history_event_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_open_houses_source'), table_name='open_houses')
    op.drop_index(op.f('ix_open_houses_property_id'), table_name='open_houses')
    op.drop_index('idx_open_houses_time_range', table_name='open_houses')
    op.drop_index('idx_open_houses_property_source', table_name='open_houses')
    op.drop_table('open_houses')
    op.drop_index(op.f('ix_leads_property_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_type'), table_name='leads')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_score', table_name='leads')
    op.drop_index('idx_leads_property_type', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_properties_zip_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_zillow_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_state'), table_name='properties')
    op.drop_index(op.f('ix_properties_redfin_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_realtor_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_listing_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.drop_index('idx_properties_state_city', table_name='properties')
    op.drop_index('idx_properties_source_count', table_name='properties')
    op.drop_index('idx_properties_created_at', table_name='properties')
    op.drop_index('idx_properties_address_zip', table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_scrape_errors_url'), table_name='scrape_errors')
    op.drop_index(op.f('ix_scrape_errors_source'), table_name='scrape_errors')
    op.drop_index('idx_scrape_errors_source_created', table_name='scrape_errors')
    op.drop_index('idx_scrape_errors_error_type', table_name='scrape_errors')
    op.drop_table('scrape_errors')
    op.drop_index(op.f('ix_raw_scrapes_url'), table_name='raw_scrapes')
    op.drop_index(op.f('ix_raw_scrapes_source'), table_name='raw_scrapes')
    op.drop_index(op.f('ix_raw_scrapes_external_id'), table_name='raw_scrapes')
    op.drop_index('idx_raw_scrapes_status', table_name='raw_scrapes')
    op.drop_index('idx_raw_scrapes_source_created', table_name='raw_scrapes')
    op.drop_table('raw_scrapes')
    # ### end Alembic commands ###
