"""Alembic script template for migrations."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb981ab6ddae'
down_revision = '4839e42f32c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_comps', sa.Column('url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_comps', 'url')
    # ### end Alembic commands ###
