"""Derived-valuation layer: market_stats, property_valuation, 5-strategy analysis.

Adds the two tables the rebuilt scoring layer reads from, extends
property_analysis with percentile/confidence per strategy plus the new
`airbnb` strategy, and restores a unique index that a previous autogenerate
silently dropped.

Written by hand rather than autogenerated, deliberately. Alembic's
autogenerate cannot represent expression indexes, so it does not see
`uq_price_history_event` in the model metadata and emits a DROP for it —
which is exactly what happened in revision 4839e42f32c8. `migrations/env.py`
now carries an `include_object` hook to stop that recurring.

Strictly additive. No existing row is read, rewritten or deleted.
"""
import logging

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3f8a1c47b92'
down_revision = 'cb981ab6ddae'
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")

UNIQUE_INDEX_NAME = "uq_price_history_event"
UNIQUE_INDEX_COLUMNS = (
    "property_id, source, event, event_date, "
    "COALESCE(price, -1), COALESCE(source_event_id, '')"
)

STRATEGIES = ("motivated_seller", "fix_flip", "buy_hold", "str", "airbnb")


def upgrade() -> None:
    """Upgrade migration."""
    _create_market_stats()
    _create_property_valuation()
    _extend_property_analysis()
    _restore_price_history_unique_index()


def _create_market_stats() -> None:
    op.create_table(
        "market_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("geo_level", sa.String(length=10), nullable=False),
        sa.Column("geo_key", sa.String(length=120), nullable=False),
        sa.Column("property_class", sa.String(length=30), nullable=False, server_default="all"),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        # sold-price baseline, from comps
        sa.Column("median_sold_ppsf", sa.Float(), nullable=True),
        sa.Column("p25_sold_ppsf", sa.Float(), nullable=True),
        sa.Column("p75_sold_ppsf", sa.Float(), nullable=True),
        sa.Column("median_sold_price", sa.Integer(), nullable=True),
        sa.Column("sold_count", sa.Integer(), nullable=False, server_default="0"),
        # listing-side baseline, from our own corpus
        sa.Column("median_list_ppsf", sa.Float(), nullable=True),
        sa.Column("median_list_price", sa.Integer(), nullable=True),
        sa.Column("median_dom", sa.Float(), nullable=True),
        sa.Column("p75_dom", sa.Float(), nullable=True),
        sa.Column("pct_listings_with_cut", sa.Float(), nullable=True),
        sa.Column("median_price_cut_pct", sa.Float(), nullable=True),
        sa.Column("listing_count", sa.Integer(), nullable=False, server_default="0"),
        # income baseline
        sa.Column("median_gross_yield", sa.Float(), nullable=True),
        sa.Column("median_rent_per_bed", sa.Float(), nullable=True),
        sa.Column("rent_sample", sa.Integer(), nullable=False, server_default="0"),
        # carrying-cost baseline
        sa.Column("median_tax_rate", sa.Float(), nullable=True),
        sa.Column("median_hoa_monthly", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_market_stats_grain", "market_stats",
        ["geo_level", "geo_key", "property_class", "as_of_date"], unique=True,
    )
    op.create_index(
        "idx_market_stats_lookup", "market_stats",
        ["geo_level", "geo_key", "property_class"], unique=False,
    )


def _create_property_valuation() -> None:
    op.create_table(
        "property_valuation",
        sa.Column("property_id", sa.UUID(), nullable=False),
        # value
        sa.Column("market_value", sa.Float(), nullable=True),
        sa.Column("market_value_method", sa.String(length=40), nullable=True),
        sa.Column("arv", sa.Float(), nullable=True),
        sa.Column("arv_method", sa.String(length=40), nullable=True),
        sa.Column("price_to_value_ratio", sa.Float(), nullable=True),
        # comp evidence
        sa.Column("comp_count", sa.Integer(), nullable=True),
        sa.Column("comp_median_ppsf", sa.Float(), nullable=True),
        sa.Column("comp_p75_ppsf", sa.Float(), nullable=True),
        sa.Column("comp_dispersion_cv", sa.Float(), nullable=True),
        sa.Column("comp_median_age_days", sa.Integer(), nullable=True),
        sa.Column("valuation_confidence", sa.Float(), nullable=True),
        # renovation
        sa.Column("rehab_cost_low", sa.Float(), nullable=True),
        sa.Column("rehab_cost_mid", sa.Float(), nullable=True),
        sa.Column("rehab_cost_high", sa.Float(), nullable=True),
        sa.Column("rehab_basis", sa.JSON(), nullable=True),
        sa.Column("condition_class", sa.String(length=20), nullable=True),
        # income
        sa.Column("rent_estimate_monthly", sa.Float(), nullable=True),
        sa.Column("rent_method", sa.String(length=30), nullable=True),
        sa.Column("rent_confidence", sa.Float(), nullable=True),
        sa.Column("gross_yield", sa.Float(), nullable=True),
        # carrying costs
        sa.Column("annual_taxes", sa.Float(), nullable=True),
        sa.Column("annual_insurance", sa.Float(), nullable=True),
        sa.Column("insurance_basis", sa.JSON(), nullable=True),
        sa.Column("annual_hoa", sa.Float(), nullable=True),
        sa.Column("annual_cdd", sa.Float(), nullable=True),
        sa.Column("annual_maintenance", sa.Float(), nullable=True),
        sa.Column("annual_operating_expenses", sa.Float(), nullable=True),
        # returns
        sa.Column("noi_annual", sa.Float(), nullable=True),
        sa.Column("cap_rate", sa.Float(), nullable=True),
        sa.Column("max_allowable_offer", sa.Float(), nullable=True),
        # resolved market context
        sa.Column("market_geo_level", sa.String(length=10), nullable=True),
        sa.Column("market_geo_key", sa.String(length=120), nullable=True),
        sa.Column("data_quality_flags", sa.JSON(), nullable=True),
        sa.Column("valuation_version", sa.String(length=20), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"]),
        sa.PrimaryKeyConstraint("property_id"),
    )
    op.create_index("idx_valuation_cap_rate", "property_valuation", ["cap_rate"], unique=False)
    op.create_index(
        "idx_valuation_price_to_value", "property_valuation", ["price_to_value_ratio"], unique=False
    )


def _extend_property_analysis() -> None:
    """Percentile + confidence for every strategy, and the new airbnb columns."""
    for strategy in STRATEGIES:
        op.add_column("property_analysis",
                      sa.Column(f"{strategy}_percentile", sa.Float(), nullable=True))
        op.add_column("property_analysis",
                      sa.Column(f"{strategy}_confidence", sa.Float(), nullable=True))
        op.create_index(
            f"ix_property_analysis_{strategy}_percentile",
            "property_analysis", [f"{strategy}_percentile"], unique=False,
        )

    # airbnb is brand new; the other four already have score/rationale/factors/flags.
    op.add_column("property_analysis", sa.Column("airbnb_score", sa.Float(), nullable=True))
    op.add_column("property_analysis", sa.Column("airbnb_rationale", sa.Text(), nullable=True))
    op.add_column("property_analysis", sa.Column("airbnb_factors", sa.JSON(), nullable=True))
    op.add_column("property_analysis", sa.Column("airbnb_flags", sa.JSON(), nullable=True))
    op.create_index(
        "ix_property_analysis_airbnb_score", "property_analysis", ["airbnb_score"], unique=False
    )


def _restore_price_history_unique_index() -> None:
    """
    Put back the guard that autogenerate removed.

    The Python-side check in PipelineRunner._upsert_price_history has held —
    there are currently zero duplicate groups — but that is the application
    being careful, not the database enforcing anything. Restore the index if
    the data still permits it, and never fail the migration over it.
    """
    bind = op.get_bind()

    duplicates = bind.execute(sa.text(f"""
        SELECT count(*) FROM (
            SELECT {UNIQUE_INDEX_COLUMNS} FROM price_history
            GROUP BY 1, 2, 3, 4, 5, 6 HAVING count(*) > 1
        ) d
    """)).scalar() or 0
    if duplicates:
        logger.warning(
            "Not restoring %s: %s duplicate group(s) present. Uniqueness stays "
            "enforced in PipelineRunner._upsert_price_history only.",
            UNIQUE_INDEX_NAME, duplicates,
        )
        return

    try:
        with bind.begin_nested():
            bind.execute(sa.text(
                f"CREATE UNIQUE INDEX IF NOT EXISTS {UNIQUE_INDEX_NAME} "
                f"ON price_history ({UNIQUE_INDEX_COLUMNS})"
            ))
        logger.info("Restored %s.", UNIQUE_INDEX_NAME)
    except Exception as exc:  # noqa: BLE001 - never fail the migration over the guard
        logger.warning("Could not restore %s (%s: %s).", UNIQUE_INDEX_NAME, type(exc).__name__, exc)


def downgrade() -> None:
    """Downgrade migration."""
    op.drop_index("ix_property_analysis_airbnb_score", table_name="property_analysis")
    for column in ("airbnb_flags", "airbnb_factors", "airbnb_rationale", "airbnb_score"):
        op.drop_column("property_analysis", column)

    for strategy in STRATEGIES:
        op.drop_index(f"ix_property_analysis_{strategy}_percentile", table_name="property_analysis")
        op.drop_column("property_analysis", f"{strategy}_confidence")
        op.drop_column("property_analysis", f"{strategy}_percentile")

    op.drop_index("idx_valuation_price_to_value", table_name="property_valuation")
    op.drop_index("idx_valuation_cap_rate", table_name="property_valuation")
    op.drop_table("property_valuation")

    op.drop_index("idx_market_stats_lookup", table_name="market_stats")
    op.drop_index("uq_market_stats_grain", table_name="market_stats")
    op.drop_table("market_stats")

    # uq_price_history_event is deliberately left in place: it is a data
    # guarantee this revision restored, not something it introduced.
